[package]
name = "db-core"
version = "0.1.0"
edition = "2024"

[features]
default = ["cloudsync"]
cloudsync = ["dep:anlg-cloudsync", "anlg-db-change/cloudsync"]
test-utils = []

[dependencies]
anlg-cloudsync = { workspace = true, optional = true }
anlg-db-change = { workspace = true, default-features = false }

backon = { workspace = true }
libsqlite3-sys = "0.35"
serde = { workspace = true, features = ["derive"] }
sqlx = { workspace = true, features = ["runtime-tokio", "sqlite"] }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt", "sync", "time"] }
tracing = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt", "time"] }
uuid = { workspace = true, features = ["v4"] }
